using System.Collections.Generic;

namespace EvasLearningWorld.Rules
{
    // Generated by tools/art-import/make-shadows.js - do not edit. The animals that have a trunk shadow (Resources/Art/zoofarm/shadow_<id>)
    // and the middle of each trunk as fractions of the animal picture (x right, y down).
    public static class TrunkShadows
    {
        public static readonly IReadOnlyDictionary<string, (float X, float Y)> Centres = new Dictionary<string, (float X, float Y)>
        {
            { "cow", (0.394f, 0.555f) },
            { "sheep", (0.395f, 0.633f) },
            { "horse", (0.558f, 0.507f) },
            { "pig", (0.382f, 0.628f) },
            { "dog", (0.558f, 0.630f) },
            { "cat", (0.503f, 0.694f) },
            { "elephant", (0.481f, 0.655f) },
            { "deer", (0.417f, 0.599f) },
            { "rhino", (0.360f, 0.598f) },
            { "giraffe", (0.412f, 0.647f) },
            { "zebra", (0.389f, 0.602f) },
            { "goat", (0.360f, 0.589f) },
            { "llama", (0.441f, 0.592f) },
            { "tiger", (0.472f, 0.635f) },
            { "wolf", (0.512f, 0.604f) },
            { "fox", (0.632f, 0.677f) },
            { "bear", (0.485f, 0.655f) },
            { "snowleopard", (0.529f, 0.649f) },
            { "gorilla", (0.541f, 0.671f) },
            { "duck", (0.427f, 0.641f) },
            { "chicken", (0.552f, 0.651f) },
            { "eagle", (0.528f, 0.637f) },
            { "owl", (0.570f, 0.708f) },
            { "swan", (0.579f, 0.679f) },
            { "turtle", (0.384f, 0.595f) },
            { "frog", (0.505f, 0.707f) },
        };
    }
}
